[package]
name = "koo_db"
version = "0.1.0"
edition = "2024"


[lib]
name="koo_db"
path="src/lib.rs"


[[example]]
name = "flexible"
path="examples/flexible_example.rs"


[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
